// sylvander-desktop/src/App.svelte
<script lang="ts">
  import crabMark from "../../docs/design/final-brand/sylvander-seed-crab-character-square.png";
  import { demoPlan, demoSessions, demoTasks, demoTranscript } from "./lib/demo";
  import type { ConnectionState, TranscriptEntry } from "./lib/types";

  let selectedId = $state(demoSessions[0].id);
  let query = $state("");
  let draft = $state("");
  let inspector = $state<"plan" | "tasks" | "changes">("plan");
  let inspectorOpen = $state(true);
  let approvalOpen = $state(true);
  let connection = $state<ConnectionState>("live");
  let transcript = $state<TranscriptEntry[]>([...demoTranscript]);
  let announcement = $state("Runtime connected");

  const selected = $derived(demoSessions.find((session) => session.id === selectedId)!);
  const filteredSessions = $derived(
    demoSessions.filter((session) =>
      `${session.label} ${session.workspace}`.toLowerCase().includes(query.toLowerCase()),
    ),
  );

  function selectSession(id: string) {
    selectedId = id;
    const session = demoSessions.find((item) => item.id === id);
    draft = session?.draft ?? "";
    announcement = `Loaded ${session?.label ?? "Session"}`;
  }

  function submit() {
    const text = draft.trim();
    if (!text || connection !== "live") return;
    transcript.push({ id: `user-${Date.now()}`, kind: "user", body: text });
    draft = "";
    announcement = "Goal submitted to the active Session";
  }

  function decide(approved: boolean) {
    approvalOpen = false;
    announcement = approved ? "Read access approved once" : "Tool request rejected";
  }

  function handleShortcut(event: KeyboardEvent) {
    if (!(event.metaKey || event.ctrlKey)) return;
    if (event.key.toLowerCase() === "k") {
      event.preventDefault();
      document.querySelector<HTMLInputElement>("#session-search")?.focus();
    }
    if (event.key.toLowerCase() === "n") {
      event.preventDefault();
      announcement = "New Session flow is ready for Runtime connection";
    }
  }
</script>

<svelte:window onkeydown={handleShortcut} />

<div class="app-shell">
  <nav class="product-rail" aria-label="Product">
    <div class="brand-mark"><img src={crabMark} alt="Sylvander Seed-Crab" /></div>
    <div class="rail-actions">
      <button class="rail-button active" aria-label="Work" aria-current="page"><span>◫</span></button>
      <button class="rail-button" aria-label="Agents"><span>◎</span></button>
      <button class="rail-button" aria-label="Automations"><span>⌁</span></button>
    </div>
    <button class="rail-button settings" aria-label="Settings"><span>⚙</span></button>
  </nav>

  <aside class="session-sidebar" aria-label="Sessions">
    <header class="sidebar-header">
      <div>
        <span class="eyebrow">Workspace</span>
        <h1>Sylvander</h1>
      </div>
      <button class="icon-button" aria-label="Create Session" title="New Session (⌘N)">＋</button>
    </header>

    <label class="session-search" for="session-search">
      <span aria-hidden="true">⌕</span>
      <input id="session-search" bind:value={query} placeholder="Find a Session" autocomplete="off" />
      <kbd>⌘K</kbd>
    </label>

    <div class="session-section-label"><span>Recent</span><span>{filteredSessions.length}</span></div>
    <div class="session-list">
      {#each filteredSessions as session (session.id)}
        <button
          class:active={session.id === selectedId}
          class="session-row"
          onclick={() => selectSession(session.id)}
          aria-current={session.id === selectedId ? "true" : undefined}
        >
          <span class:active={session.state === "active"} class:waiting={session.state === "waiting"} class="presence"></span>
          <span class="session-copy">
            <strong>{session.label}</strong>
            <span>{session.workspace}</span>
          </span>
          <time>{session.recency}</time>
        </button>
      {/each}
    </div>

    <footer class="runtime-card">
      <span class:live={connection === "live"} class="runtime-dot"></span>
      <div><strong>Local Runtime</strong><span>{connection === "live" ? "Connected" : connection}</span></div>
      <button aria-label="Runtime details">···</button>
    </footer>
  </aside>

  <main class="conversation" aria-label="Conversation">
    <header class="conversation-header">
      <div class="session-heading">
        <span class="presence active"></span>
        <div><h2>{selected.label}</h2><p>{selected.workspace}</p></div>
      </div>
      <div class="header-actions">
        <button class="quiet-button" onclick={() => (inspectorOpen = !inspectorOpen)} aria-pressed={inspectorOpen}>Plan <span>3/5</span></button>
        <button class="icon-button" aria-label="Session actions">···</button>
      </div>
    </header>

    <section class="transcript" aria-label="Transcript">
      <div class="session-intro">
        <span class="eyebrow">Agent workspace</span>
        <h3>Build with a clear trail from intent to evidence.</h3>
        <p>Agent <strong>sylvander</strong> · MiniMax-M2.7 · standard permissions</p>
      </div>

      {#each transcript as entry (entry.id)}
        <article class="turn {entry.kind}" data-status={entry.status}>
          <span class="turn-mark" aria-hidden="true">{entry.kind === "user" ? "❯" : entry.kind === "tool" ? "⎿" : "⏺"}</span>
          <div class="turn-content">
            {#if entry.title}<strong class="turn-title">{entry.title}</strong>{/if}
            <p>{entry.body}</p>
            {#if entry.meta}<span class="turn-meta">{entry.status === "verified" ? "✓ " : entry.status === "running" ? "↻ " : ""}{entry.meta}</span>{/if}
          </div>
          {#if entry.kind === "tool"}<button class="inspect-button" onclick={() => (inspectorOpen = true)}>Inspect</button>{/if}
        </article>
      {/each}
    </section>

    <div class="interaction-zone">
      {#if approvalOpen}
        <section class="decision-dock" aria-labelledby="approval-title">
          <div class="decision-icon" aria-hidden="true">◇</div>
          <div class="decision-copy">
            <span class="eyebrow">Approval · this Session</span>
            <h3 id="approval-title">Allow Read to inspect the desktop package?</h3>
            <p><code>Read</code> requests workspace read access for <code>sylvander-desktop/</code>.</p>
          </div>
          <div class="decision-actions">
            <button class="secondary-button" onclick={() => decide(false)}>Reject</button>
            <button class="primary-button" onclick={() => decide(true)}>Allow once</button>
          </div>
        </section>
      {/if}

      <form class="composer" onsubmit={(event) => { event.preventDefault(); submit(); }}>
        <label for="composer-input" class="sr-only">Message Sylvander</label>
        <textarea id="composer-input" bind:value={draft} rows="2" placeholder="What should we work through?" onkeydown={(event) => {
          if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); submit(); }
        }}></textarea>
        <div class="composer-footer">
          <div class="composer-tools">
            <button type="button" aria-label="Attach context">＋</button>
            <button type="button">Standard <span>⌄</span></button>
            <button type="button">MiniMax-M2.7 <span>⌄</span></button>
          </div>
          <div class="send-group"><span><kbd>↵</kbd> send · <kbd>⇧↵</kbd> line</span><button class="send-button" disabled={!draft.trim() || connection !== "live"} aria-label="Send">↑</button></div>
        </div>
      </form>
    </div>
  </main>

  {#if inspectorOpen}
    <aside class="inspector" aria-label="Session inspector">
      <header><div><span class="eyebrow">Live work</span><h2>Execution</h2></div><button class="icon-button" onclick={() => (inspectorOpen = false)} aria-label="Close inspector">×</button></header>
      <div class="inspector-tabs" role="tablist" aria-label="Execution details">
        {#each ["plan", "tasks", "changes"] as tab}
          <button role="tab" aria-selected={inspector === tab} class:active={inspector === tab} onclick={() => (inspector = tab as typeof inspector)}>{tab}</button>
        {/each}
      </div>
      {#if inspector === "plan"}
        <ol class="plan-list">
          {#each demoPlan as step, index}
            <li data-state={step.state}><span>{step.state === "complete" ? "✓" : index + 1}</span><p>{step.label}</p></li>
          {/each}
        </ol>
      {:else if inspector === "tasks"}
        <div class="task-list">{#each demoTasks as task}<article><span class="presence" class:active={task.state === "running"}></span><div><strong>{task.purpose}</strong><p>{task.owner} · {task.state}</p></div></article>{/each}</div>
      {:else}
        <div class="empty-inspector"><span>±</span><h3>No reviewable diff yet</h3><p>Runtime-owned changes will appear here.</p></div>
      {/if}
      <footer class="inspector-summary"><span>Context</span><strong>18.4k / 128k</strong><div><span style="width: 14%"></span></div></footer>
    </aside>
  {/if}

  <div class="sr-only" aria-live="polite">{announcement}</div>
</div>

// sylvander-work/src/App.tsx
import { FormEvent, KeyboardEvent, useEffect, useMemo, useState } from "react";

import crabMark from "../../docs/design/final-brand/sylvander-seed-crab-character-square.png";
import type { RuntimeGatewayPort } from "./lib/gateway";
import { useRuntime } from "./lib/useRuntime";

export interface AppProps {
  gateway?: RuntimeGatewayPort;
}

export default function App({ gateway }: AppProps) {
  const { state, selectSession, submit, answerQuestion, resolvePlan } = useRuntime(gateway);
  const [query, setQuery] = useState("");
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const [inspector, setInspector] = useState<"plan" | "tasks" | "changes">("plan");
  const [inspectorOpen, setInspectorOpen] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [questionSelections, setQuestionSelections] = useState<string[]>([]);
  const [questionText, setQuestionText] = useState("");
  const [compactLayout, setCompactLayout] = useState(() =>
    typeof matchMedia === "function" && matchMedia("(max-width: 860px)").matches);
  const selected = state.sessions.find((session) => session.id === state.selectedId);
  const draft = state.selectedId ? drafts[state.selectedId] ?? "" : "";
  const visibleSessions = useMemo(() => {
    const needle = query.toLowerCase();
    return state.sessions.filter((session) => `${session.label} ${session.workspace}`.toLowerCase().includes(needle));
  }, [query, state.sessions]);

  useEffect(() => {
    if (typeof matchMedia !== "function") return;
    const query = matchMedia("(max-width: 860px)");
    const update = () => setCompactLayout(query.matches);
    query.addEventListener("change", update);
    update();
    return () => query.removeEventListener("change", update);
  }, []);

  function updateDraft(value: string) {
    if (state.selectedId) setDrafts((current) => ({ ...current, [state.selectedId!]: value }));
  }

  async function send(event?: FormEvent) {
    event?.preventDefault();
    if (!state.selectedId || state.connection !== "live" || !draft.trim()) return;
    await submit({ type: "chat", text: draft.trim(), attachments: [], session_id: state.selectedId });
    updateDraft("");
  }

  function handleComposerKey(event: KeyboardEvent<HTMLTextAreaElement>) {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      void send();
    }
  }

  async function decide(callId: string, approved: boolean) {
    if (!state.approval) return;
    await submit({
      type: "approve",
      session_id: state.approval.sessionId,
      call_id: callId,
      approved,
      scope: "once",
    });
  }

  function toggleQuestionOption(option: string) {
    if (!state.question?.multiSelect) {
      setQuestionSelections([option]);
      return;
    }
    setQuestionSelections((current) => current.includes(option)
      ? current.filter((candidate) => candidate !== option)
      : [...current, option]);
  }

  async function submitQuestion(event: FormEvent) {
    event.preventDefault();
    if (!state.question) return;
    const selected = questionSelections.join(", ");
    const detail = questionText.trim();
    const answer = selected && detail ? `${selected}; ${detail}` : selected || detail;
    if (!answer) return;
    await answerQuestion(state.question.callId, answer);
    setQuestionSelections([]);
    setQuestionText("");
  }

  return <div className="app-shell">
    <nav className="product-rail" aria-label="Product">
      <div className="brand-mark"><img src={crabMark} alt="Sylvander Seed-Crab" /></div>
      <div className="rail-actions">
        <button className="rail-button active" aria-label="Work" aria-current="page" aria-expanded={sidebarOpen} onClick={() => setSidebarOpen(!sidebarOpen)}><span>◫</span></button>
        <button className="rail-button" aria-label="Agents"><span>◎</span></button>
        <button className="rail-button" aria-label="Automations"><span>⌁</span></button>
      </div>
      <button className="rail-button settings" aria-label="Settings"><span>⚙</span></button>
    </nav>

    <aside
      className={`session-sidebar${sidebarOpen ? " open" : ""}`}
      aria-label="Sessions"
      aria-hidden={compactLayout && !sidebarOpen ? true : undefined}
      inert={compactLayout && !sidebarOpen ? true : undefined}
    >
      <header className="sidebar-header">
        <div><span className="eyebrow">Workspace</span><h1>Sylvander Work</h1></div>
        <button className="icon-button" aria-label="Create Session">＋</button>
      </header>
      <label className="session-search" htmlFor="session-search">
        <span aria-hidden="true">⌕</span>
        <input id="session-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a Session" autoComplete="off" />
        <kbd>⌘K</kbd>
      </label>
      <div className="session-section-label"><span>Recent</span><span>{visibleSessions.length}</span></div>
      <div className="session-list">
        {visibleSessions.map((session) => <button
          key={session.id}
          className={`session-row${session.id === state.selectedId ? " active" : ""}`}
          onClick={() => { void selectSession(session.id); setSidebarOpen(false); }}
          aria-current={session.id === state.selectedId ? "true" : undefined}
        >
          <span className={`presence ${session.state}`} />
          <span className="session-copy"><strong>{session.label}</strong><span>{session.workspace}</span></span>
          <time>{session.recency}</time>
        </button>)}
      </div>
      <footer className="runtime-card">
        <span className={`runtime-dot ${state.connection}`} />
        <div><strong>Local Runtime</strong><span>{connectionLabel(state.connection)}</span></div>
        <button aria-label="Runtime details">···</button>
      </footer>
    </aside>

    <main className="conversation" aria-label="Conversation">
      <header className="conversation-header">
        <div className="session-heading">
          <button className="mobile-nav" aria-label="Open Sessions" aria-expanded={sidebarOpen} onClick={() => setSidebarOpen(!sidebarOpen)}>◫</button>
          <span className={`presence ${selected?.state ?? "idle"}`} />
          <div><h2>{selected?.label ?? "No Session selected"}</h2><p>{selected?.workspace ?? "Connect Runtime to continue"}</p></div>
        </div>
        <div className="header-actions">
          <button className="quiet-button" onClick={() => setInspectorOpen(!inspectorOpen)} aria-pressed={inspectorOpen}>Plan <span>{state.plan.filter((step) => step.state === "complete").length}/{state.plan.length}</span></button>
          <button className="icon-button" aria-label="Session actions">···</button>
        </div>
      </header>

      <section className="transcript" aria-label="Transcript">
        {state.connection !== "live" && <div className="session-intro">
          <span className="eyebrow">Rust Runtime</span>
          <h3>{state.connection === "offline" ? "Runtime is unavailable." : "Connecting the desktop workspace…"}</h3>
          <p>{state.diagnostic ?? "The native gateway is negotiating the authenticated UI protocol."}</p>
        </div>}
        {state.connection === "live" && !selected && <div className="session-intro">
          <span className="eyebrow">Agent workspace</span>
          <h3>Start with a durable Session.</h3>
          <p>Sessions, authorization, tools, and evidence remain Runtime-owned.</p>
        </div>}
        {state.transcript.map((entry) => <article key={entry.id} className={`turn ${entry.kind}`} data-status={entry.status}>
          <span className="turn-mark" aria-hidden="true">{entry.kind === "user" ? "❯" : entry.kind === "tool" ? "⎿" : "⏺"}</span>
          <div className="turn-content">
            {entry.title && <strong className="turn-title">{entry.title}</strong>}
            <p>{entry.body}</p>
            {entry.meta && <span className="turn-meta">{entry.meta}</span>}
          </div>
          {entry.kind === "tool" && <button className="inspect-button" onClick={() => setInspectorOpen(true)}>Inspect</button>}
        </article>)}
      </section>

      <div className="interaction-zone">
        {state.question && <form className="decision-dock" aria-labelledby="question-title" onSubmit={(event) => void submitQuestion(event)}>
          <div className="decision-icon" aria-hidden="true">?</div>
          <div className="decision-copy"><span className="eyebrow">Agent asks</span><h3 id="question-title">{state.question.prompt}</h3><div className="question-options">{state.question.options.map((option) => <label key={option}><input type={state.question!.multiSelect ? "checkbox" : "radio"} name="agent-question" checked={questionSelections.includes(option)} onChange={() => toggleQuestionOption(option)} /> {option}</label>)}</div><input aria-label="Other answer" value={questionText} onChange={(event) => setQuestionText(event.target.value)} placeholder={state.question.options.length > 0 ? "Other or additional context" : "Your answer"} /></div>
          <div className="decision-actions"><button className="primary-button" disabled={questionSelections.length === 0 && !questionText.trim()}>Answer</button></div>
        </form>}
        {state.approval && state.approval.tools[0] && <section className="decision-dock" aria-labelledby="approval-title">
          <div className="decision-icon" aria-hidden="true">◇</div>
          <div className="decision-copy"><span className="eyebrow">Approval · {state.approval.tools.length} pending</span><h3 id="approval-title">Allow {state.approval.tools[0].toolName}?</h3><p>Runtime is waiting for the least-authorizing decision.</p></div>
          <div className="decision-actions"><button className="secondary-button" onClick={() => void decide(state.approval!.tools[0].callId, false)}>Reject</button><button className="primary-button" onClick={() => void decide(state.approval!.tools[0].callId, true)}>Allow once</button></div>
        </section>}
        <form className="composer" onSubmit={(event) => void send(event)}>
          <label htmlFor="composer-input" className="sr-only">Message Sylvander</label>
          <textarea id="composer-input" value={draft} onChange={(event) => updateDraft(event.target.value)} rows={2} placeholder="What should we work through?" onKeyDown={handleComposerKey} disabled={!selected || state.connection !== "live"} />
          <div className="composer-footer">
            <div className="composer-tools"><button type="button" aria-label="Attach context">＋</button><button type="button">Standard <span>⌄</span></button><button type="button">Runtime model <span>⌄</span></button></div>
            <div className="send-group"><span><kbd>↵</kbd> send · <kbd>⇧↵</kbd> line</span><button className="send-button" disabled={!draft.trim() || !selected || state.connection !== "live"} aria-label="Send">↑</button></div>
          </div>
        </form>
      </div>
    </main>

    {inspectorOpen && <aside className="inspector" aria-label="Session inspector">
      <header><div><span className="eyebrow">Live work</span><h2>Execution</h2></div><button className="icon-button" onClick={() => setInspectorOpen(false)} aria-label="Close inspector">×</button></header>
      <div className="inspector-tabs" role="tablist" aria-label="Execution details">
        {(["plan", "tasks", "changes"] as const).map((tab) => <button key={tab} role="tab" aria-selected={inspector === tab} className={inspector === tab ? "active" : ""} onClick={() => setInspector(tab)}>{tab}</button>)}
      </div>
      {inspector === "plan" && <ol className="plan-list">{state.plan.map((step, index) => <li key={`${index}-${step.label}`} data-state={step.state}><span>{step.state === "complete" ? "✓" : index + 1}</span><p>{step.label}</p></li>)}</ol>}
      {inspector === "plan" && state.activePlan && <div className="decision-actions"><button className="secondary-button" onClick={() => void resolvePlan(state.activePlan!.planId, { decision: "rejected", reason: "cancelled by user" })}>Reject plan</button><button className="primary-button" onClick={() => void resolvePlan(state.activePlan!.planId, { decision: "approved" })}>Approve plan</button></div>}
      {inspector === "tasks" && <div className="task-list">{state.tasks.map((task) => <article key={task.id}><span className={`presence ${task.state}`} /><div><strong>{task.purpose}</strong><p>{task.owner} · {task.state}{task.detail ? ` · ${task.detail}` : ""}</p></div></article>)}</div>}
      {inspector === "changes" && <div className="empty-inspector"><span>±</span><h3>No reviewable diff</h3><p>Runtime-owned changes will appear here.</p></div>}
      <footer className="inspector-summary"><span>Protocol</span><strong>v5</strong><div><span style={{ width: state.connection === "live" ? "100%" : "0%" }} /></div></footer>
    </aside>}
    <div className="sr-only" aria-live="polite">{connectionLabel(state.connection)}</div>
  </div>;
}

function connectionLabel(state: string) {
  return state === "live" ? "Connected" : state.charAt(0).toUpperCase() + state.slice(1);
}
